# Configures the build pipeline dependencies for openshift
# See: README.md

apiVersion: v1
kind: List
metadata:
  name: my-telus-spacejam-pipeline
items:

# Configure our Docker App image repository
# https://docs.openshift.com/enterprise/3.2/dev_guide/managing_images.html
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: my-telus-spacejam
    labels:
      app: my-telus-spacejam

# Configure our Docker e2e image repository
# https://docs.openshift.com/enterprise/3.2/dev_guide/managing_images.html
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: my-telus-spacejam-e2e
    labels:
      app: my-telus-spacejam

# Configure our Docker load test image repository
# https://docs.openshift.com/enterprise/3.2/dev_guide/managing_images.html
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: my-telus-spacejam-load
    labels:
      app: my-telus-spacejam

# Configure our Docker load test image repository
# https://docs.openshift.com/enterprise/3.2/dev_guide/managing_images.html
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: my-telus-spacejam-lighthouse
    labels:
      app: my-telus-spacejam

# Configure our build pipeline template
# https://docs.openshift.com/enterprise/3.2/dev_guide/templates.html
- apiVersion: v1
  kind: Template
  metadata:
    name: my-telus-spacejam-pipeline
  parameters:
  - name: BRANCH
    description: Branch to build from
    value: master
  objects:

  # Configures the OpenShift/Jenkins build pipeline
  # https://docs.openshift.com/enterprise/3.2/dev_guide/builds.html#defining-a-buildconfig
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: my-telus-spacejam-pipeline
      labels:
        app: my-telus-spacejam
    spec:
      source:
        type: Git
        git:
          uri: git@github.com:telus/my-telus-spacejam.git
          ref: ${BRANCH}
        sourceSecret:
          name: github-secret
      triggers:
        - type: GitHub
          github:
            secret: tisk
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi
      runPolicy: SerialLatestOnly
      strategy:
        type: JenkinsPipeline
        jenkinsPipelineStrategy:
          jenkinsfilePath: Jenkinsfile

  # Configure our Docker App container build
  # https://docs.openshift.com/enterprise/3.2/architecture/core_concepts/builds_and_image_streams.html#docker-build
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: my-telus-spacejam
      labels:
        app: my-telus-spacejam
    spec:
      source:
        type: Git
        git:
          uri: git@github.com:telus/my-telus-spacejam.git
          ref: ${BRANCH}
        contextDir: app
        sourceSecret:
          name: github-secret
        secrets:
          - secret:
              name: npmrc-secret
        runPolicy: Parallel
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
          forcePull: true
      output:
        to:
          kind: ImageStreamTag
          name: my-telus-spacejam:latest

  # Configure our Docker e2e container build
  # https://docs.openshift.com/enterprise/3.2/architecture/core_concepts/builds_and_image_streams.html#docker-build
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: my-telus-spacejam-e2e
      labels:
        app: my-telus-spacejam
    spec:
      source:
        type: Git
        git:
          uri: git@github.com:telus/my-telus-spacejam.git
          ref: ${BRANCH}
        contextDir: e2e
        sourceSecret:
          name: github-secret
        secrets:
          - secret:
              name: npmrc-secret
        runPolicy: Parallel
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
          forcePull: true
      output:
        to:
          kind: ImageStreamTag
          name: my-telus-spacejam-e2e:latest
  # Configure our Docker load container build
  # https://docs.openshift.com/enterprise/3.2/architecture/core_concepts/builds_and_image_streams.html#docker-build
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: my-telus-spacejam-load
      labels:
        app: my-telus-spacejam
    spec:
      source:
        type: Git
        git:
          uri: git@github.com:telus/my-telus-spacejam.git
          ref: ${BRANCH}
        contextDir: load-test
        sourceSecret:
          name: github-secret
        runPolicy: Parallel
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
          forcePull: true
      output:
        to:
          kind: ImageStreamTag
          name: my-telus-spacejam-load:latest

  # Configure our Docker lighthouse container build
  # https://docs.openshift.com/enterprise/3.2/architecture/core_concepts/builds_and_image_streams.html#docker-build
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: my-telus-spacejam-lighthouse
      labels:
        app: my-telus-spacejam
    spec:
      source:
        type: Git
        git:
          uri: git@github.com:telus/my-telus-spacejam.git
          ref: ${BRANCH}
        contextDir: lighthouse-test
        sourceSecret:
          name: github-secret
        secrets:
          - secret:
              name: npmrc-secret
        runPolicy: Parallel
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
          forcePull: true
      output:
        to:
          kind: ImageStreamTag
          name: my-telus-spacejam-lighthouse:latest

# Configure our deployment template
# https://docs.openshift.com/enterprise/3.2/dev_guide/templates.html
- apiVersion: v1
  kind: Template
  metadata:
    name: my-telus-spacejam
  parameters:
  - name: VERSION
    value: ''
  - name: ENVIRONMENT
    description: The environment name
    value: production
  - name: DOCKER_REGISTRY
    description: Docker App image to deploy
  - name: NUM_REPLICAS
    description: How many replicas of the pod to deploy?
    value: '1'
  - name: MAX_REPLICAS
    description: Limit on number of replicas to create
    value: '5'
  objects:

  # How the container is deployed
  # https://docs.openshift.com/enterprise/3.2/dev_guide/deployments.html
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: my-telus-spacejam-${ENVIRONMENT}
      labels:
        app: my-telus-spacejam
        version: ${VERSION}
    spec:
      replicas: ${{NUM_REPLICAS}}
      template:
        metadata:
          labels:
            deploymentconfig: my-telus-spacejam-${ENVIRONMENT}
        spec:
          containers:
            - name: my-telus-spacejam
              image: ${DOCKER_REGISTRY}
              imagePullPolicy: Always
              env:
                - name: APP_ENV
                  value: ${ENVIRONMENT}
                - name: NEW_RELIC_APP_NAME
                  value: "my-telus-spacejam (${ENVIRONMENT})"
                - name: NEW_RELIC_ENABLED
                  value: 'true'
                - name: NEW_RELIC_LICENSE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: newrelic-license-secret
                      key: newrelic-license
              ports:
                - containerPort: 3000
              livenessProbe:
                tcpSocket:
                  port: 3000
                initialDelaySeconds: 1
                timeoutSeconds: 1
              readinessProbe:
                httpGet:
                  path: /version
                  port: 3000
                initialDelaySeconds: 1
                timeoutSeconds: 1
              resources:
                requests:
                  cpu: 500m
                  memory: 512Mi
                limits:
                  cpu: 1000m
                  memory: 1Gi
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: telus-isomorphic-starter-kit-contrast
      labels:
        app: telus-isomorphic-starter-kit-contrast
        version: ${VERSION}
    spec:
      replicas: ${{NUM_REPLICAS}}
      template:
        metadata:
          labels:
            deploymentconfig: telus-isomorphic-starter-kit-contrast
        spec:
          containers:
            - name: telus-isomorphic-starter-kit-contrast
              command:
                - npm
                - run
                - contrast
              image: ${DOCKER_REGISTRY}
              imagePullPolicy: Always
              env:
                - name: APP_ENV
                  value: development
                - name: NEW_RELIC_APP_NAME
                  value: "telus-isomorphic-starter-kit (contrast)"
                - name: NEW_RELIC_ENABLED
                  value: 'true'
                - name: NEW_RELIC_LICENSE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: newrelic-license-secret
                      key: newrelic-license
              ports:
                - containerPort: 3000
              livenessProbe:
                tcpSocket:
                  port: 3000
                initialDelaySeconds: 3
                timeoutSeconds: 3
              readinessProbe:
                httpGet:
                  path: /version
                  port: 3000
                initialDelaySeconds: 6
                timeoutSeconds: 6
              resources:
                requests:
                  cpu: 500m
                  memory: 512Mi
                limits:
                  cpu: 1000m
                  memory: 1Gi
              volumeMounts:
                - name: contrast-volume
                  mountPath: /app/contrast
                  readOnly: true
          volumes:
            - name: contrast-volume
              secret:
                secretName: contrast-dev

  # How the app container is load balanced
  # https://docs.openshift.com/enterprise/3.2/architecture/core_concepts/pods_and_services.html
  - apiVersion: v1
    kind: Service
    metadata:
      name: my-telus-spacejam-${ENVIRONMENT}
      labels:
        app: my-telus-spacejam
    spec:
      ports:
        - name: app
          port: 3000
          targetPort: 3000
      selector:
        deploymentconfig: my-telus-spacejam-${ENVIRONMENT}

  # How the app container is exposed
  # https://docs.openshift.com/enterprise/3.2/dev_guide/routes.html
  - apiVersion: v1
    kind: Route
    metadata:
      name: my-telus-spacejam-${ENVIRONMENT}
      labels:
        app: my-telus-spacejam
      annotations:
        haproxy.router.openshift.io/disable_cookies: 'true'
    spec:
      to:
        kind: Service
        name: my-telus-spacejam-${ENVIRONMENT}
        weight: 100
      port:
        targetPort: 3000
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect

  # How the container is scaled
  # https://docs.openshift.com/enterprise/3.2/dev_guide/pod_autoscaling.html
  - apiVersion: autoscaling/v1
    kind: HorizontalPodAutoscaler
    metadata:
      name: my-telus-spacejam-${ENVIRONMENT}
      labels:
        app: my-telus-spacejam
    spec:
      scaleTargetRef:
        apiVersion: v1
        kind: DeploymentConfig
        name: my-telus-spacejam-${ENVIRONMENT}
      minReplicas: ${{NUM_REPLICAS}}
      maxReplicas: ${{MAX_REPLICAS}}
      targetCPUUtilizationPercentage: 80
